
[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/viper"
    version="v1.2.0"

[[constraint]]
    name="github.com/prometheus/common"
    branch="master"

[[constraint]]
    name="github.com/yourbasic/graph"
    version="v1.0.5"

[[constraint]]
    name="github.com/nalej/grpc-utils"
    version="v1.2.0"

[[constraint]]
    name="github.com/nalej/grpc-conductor-go"
    version="v0.0.61"

[[constraint]]
    name="github.com/nalej/grpc-application-go"
    version="v0.0.20"

[[constraint]]
    name="github.com/nalej/grpc-organization-go"
    version="v0.0.15"

[[constraint]]
    name="github.com/nalej/grpc-deployment-manager-go"
    version="v0.0.30"

[[constraint]]
    name="github.com/nalej/grpc-app-cluster-api-go"
    version="v0.0.1"

[[constraint]]
    name="github.com/nalej/grpc-infrastructure-go"
    version="v0.0.13"

[[constraint]]
    name="github.com/nalej/grpc-network-go"
    version="v0.0.21"


 [[constraint]]
   name="github.com/onsi/ginkgo"
   version="v1.6.0"

[[constraint]]
    name="github.com/onsi/gomega"
    version="v1.4.2"

 [[override]]
   source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
   name = "gopkg.in/fsnotify.v1"

 [[constraint]]
    name = "github.com/phf/go-queue"
    branch = "master"

 [[constraint]]
    name = "github.com/google/uuid"
    version = "v1.0.0"