
[[constraint]]
    name="github.com/spf13/cobra"
    version="v0.0.3"

[[constraint]]
    name="github.com/rs/zerolog"
    version="v1.8.0"

[[constraint]]
    name="github.com/spf13/viper"
    version="v1.2.0"

[[constraint]]
    name="github.com/prometheus/common"
