#%RAML 1.0 DataType

displayName: DeployAppRequest
description: |
Request to deploy an application
type: object
properties:
  appDescriptorId: string
  name: string
  description: string
  label: string
  arguments: string
  persistenceSize: string
  storageType: string
example:
  appDescriptorId: app00001
  name: Example Application
  description: Basic application deployment
  label: cloud
  arguments: --port=1234
  persistenceSize: 1Gb
  storageType: default
