#RAML 1.0
title: Conductor API
version: v1
baseUri: http://conductor/api/{version}
description: |
  The conductor API orchestrates daisho applications.
types:
  ApplicationInstance: !include dataTypes/applicationInstance.raml
  DeployAppRequest: !include dataTypes/deployAppRequest.raml

# Endpoints
/app:
  /{networkId}:
    /deploy:
      uriParameters:
        networkId:
          type: string
          displayName: Target network id.
        post:
          displayName: Deploy an application
          body:
            application/json:
            type: DeployAppRequest
          responses:
            200:
              description: If the app is deployed
              body:
              application/json:
              type: ApplicationInstance
            500:
              description: The application could not be deployed.
    /{instanceId}:
      uriParameters:
        networkId:
          type: string
          displayName: Target networkId
        instanceId:
          type: string
          displayName: Identifier for the deployed instance Id
        get:
          displayName: Undeploy an already deployed application
          responses:
            200:
              description: The appication was correctly undeployed.
            500:
              description: The application could not be undeployed.
