###
# Conductor configuration
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: conductor
  name: conductor
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: conductor
  template:
    metadata:
      labels:
        cluster: management
        component: conductor
    spec:
      containers:
      - name: conductor
        image: nalej/conductor:VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
        args:
          - "run"
          - "--debug"
          - "--systemModelAddress=system-model.nalej:8800"
          - "--networkManagerAddress=network-manager.nalej:8000"
        ports:
        - name: api-port
          containerPort: 5000