kind: Service
apiVersion: v1
metadata:
  name: conductor
  namespace: __NPH_NAMESPACE
  labels:
    cluster: management
    component: conductor
spec:
  selector:
    cluster: management
    component: conductor
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
