###
# Conductor configuration
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: conductor
  name: conductor
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: conductor
  template:
    metadata:
      labels:
        cluster: management
        component: conductor
    spec:
      securityContext:
        runAsUser: 2000
        fsGroup: 2000
      containers:
      - name: conductor
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/conductor:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
          - "run"
          - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
          - "--networkManagerAddress=network-manager.__NPH_NAMESPACE:8000"
          - "--authxAddress=authx.__NPH_NAMESPACE:8810"
          - "--unifiedLogging=unified-logging-coord.__NPH_NAMESPACE:8323"
          - "--queueAddress=broker.__NPH_NAMESPACE:6650"
          - "--dbFolder=/data"
          - "--caCertPath=/nalej/ca-certificate/ca.crt"
          - "--clientCertPath=/nalej/tls-client-certificate/"
          - "--skipServerCertValidation=false"
        ports:
        - name: api-port
          containerPort: 5000
        volumeMounts:
        - name: conductor-local-db
          mountPath: /data
        - name: tls-client-certificate-volume
          readOnly: true
          mountPath: /nalej/tls-client-certificate
        - name: ca-certificate-volume
          readOnly: true
          mountPath: /nalej/ca-certificate
      imagePullSecrets:
      - name: nalej-registry
      volumes:
      - name: conductor-local-db
        persistentVolumeClaim:
          claimName: conductor-local-db
      - name: tls-client-certificate-volume
        secret:
          secretName: tls-client-certificate
      - name: ca-certificate-volume
        secret:
          secretName: ca-certificate