###
# Conductor configuration
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: conductor
  name: conductor
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: conductor
  template:
    metadata:
      labels:
        cluster: management
        component: conductor
    spec:
      containers:
      - name: conductor
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/conductor:__NPH_VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
          - "run"
          - "--debug"
          - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
          - "--networkManagerAddress=network-manager.__NPH_NAMESPACE:8000"
          - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        ports:
        - name: api-port
          containerPort: 5000
      imagePullSecrets:
      - name: nalej-registry
