apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cluster: management
    component: conductor
  name: conductor-local-db
  namespace: __NPH_NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-premium