kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: musician
  name: musician
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: musician
  template:
    metadata:
      labels:
        cluster: application
        component: musician
    spec:
      containers:
      - name: musician
        env:
          - name: CLUSTER_ID
            valueFrom:
              configMapKeyRef:
                name: cluster-config
                key: cluster_id
        image: nalejregistry.azurecr.io/nalej/conductor:VERSION
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
        - "musician"
        - "--prometheus=http://prometheus.nalej.svc.cluster.local:9090"
        #- "--debug"
        ports:
        - name: musician-port
          containerPort: 5100
      imagePullSecrets:
      - name: nalej-registry
