kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: samurai
    component: conductor
  name: conductor
  namespace: daisho
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: samurai
      component: conductor
  template:
    metadata:
      labels:
        app: samurai
        component: conductor
    spec:
      containers:
      - name: conductor
        image: registry.fmx.cloud/daisho/conductor:v1.0.1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
        args:
          - "--system-model-address=http://system-model.daisho.svc.cluster.local:8800"
          - "--logger-address=http://log-collector.kube-system.svc.cluster.local:8083"
        ports:
        - name: api-port
          containerPort: 9000
        readinessProbe:
          httpGet:
            path: /ping
            port: api-port
---
kind: Service
apiVersion: v1
metadata:
  name: conductor
  namespace: daisho
spec:
  selector:
    app: samurai
    component: conductor
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
