kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: musician
  name: musician
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: musician
  template:
    metadata:
      labels:
        cluster: management
        component: musician
    spec:
      containers:
      - name: musician
        image: nalejregistry.azurecr.io/nalej/conductor:VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
        args:
        - "musician"
        - "--prometheus=prometheus.nalej.svc.cluster.local:9090"
        #- "--debug"
        ports:
        - name: musician-port
          containerPort: 5100
      imagePullSecrets:
      - name: nalej-registry
