kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    component: prometheus
    cluster: application
  name: node-exporter
  namespace: nalej
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  resourceNames:
  - node-exporter