kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  labels:
    component: prometheus
    cluster: application
  name: node-exporter
  namespace: nalej
spec:
  privileged: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - min: 9100
    max: 9100
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
