apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: __NPH_NAMESPACE
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    component: prometheus
    cluster: application
