apiVersion: v1
kind: Service
metadata:
  labels:
    component: prometheus
    cluster: application
  name: prometheus
  namespace: nalej
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 31080
  selector:
    name: prometheus
  type: NodePort